### ISSUE TITLE
Save in the same directory as the source file

### ISSUE THREAD

**Issue by BurhanDanger** [Ajatt-Tools/videoclip#1]
Is there a way to configure it such?

Great script BTW!

**Comment by tatsumoto-ren** [comment]
Thank you for your comment! Currently there's no config option to do that. By default videos are saved in a separate folder. I may try to add it though, I don't think it's going to be a particularly difficult task.

**Comment by BurhanDanger** [comment]
Oh okay. Thanks. It was just a question.
