### ISSUE TITLE
Error: Audio streams are not allowed.

### ISSUE THREAD

**Issue by objestik** [Ajatt-Tools/videoclip#11]
Making a video clip with MPV and posting it on 4chan gives me this error message. : Error: Audio streams are not allowed.
I made sure to choose vp8 format and mute audio in the options menu.

**Comment by tatsumoto-ren** [comment]
Yes, if you want to post a clip on 4chan you have to mute audio and use vp8. However, to post clips on Telegram it is recommended to use mp4 and aac.
