### ISSUE TITLE
Add it mplug script directory

### ISSUE THREAD

**Issue by z8512** [Ajatt-Tools/videoclip#13]
Mplug is like a package manager but for mpv scripts.
Please add your script there (if already not there) and also installation instructions in manifest - https://github.com/Nudin/mpv-script-directory/blob/master/HOWTO_ADD_INSTALL_INSTRUCTIONS.md

**Comment by tatsumoto-ren** [comment]
Hello. Thanks for the request. Unfortunately, I don't know how to do what you ask, help is needed.

**Comment by z8512** [comment]
Hello @tatsumoto-ren its very simple. First check https://nudin.github.io/mpv-script-directory whether your script(s) are present there, if not then open pull request to add your script. Then finally you'll have to write manifest for your script. Instructions here https://github.com/Nudin/mpv-script-directory/blob/master/HOWTO_ADD_INSTALL_INSTRUCTIONS.md

**Comment by z8512** [comment]
Hope it helps

**Comment by Koopzington** [comment]
So i saw this issue and *thought* it would be relatively easy to pull off, despite not knowing anything about mplug or mpv plugins in general and i realized that there's currently only two options for solving this:
- mplug implements support for plugins contained in folders with a `main.{ext}` file
- this plugin gets rewritten into a single `videoclip.lua`

**Comment by tatsumoto-ren** [comment]
Yeah you probably don't really need mplug since you can simply `git clone` this repo into the scripts directory.

**Comment by Koopzington** [comment]
The point is to have a simple central way to manage your mpv plugins.
Sure, `cd`ing into every folder and doing a `git pull` to manually update them works too but takes more time than a `mplug upgrade`.
Aside from that, being listed on https://nudin.github.io/mpv-script-directory/ would be free advertising for your script.

**Comment by tatsumoto-ren** [comment]
Alternatively, you can install all your scripts as git submodules of your dotfiles. [Example](https://github.com/tatsumoto-ren/dotfiles/blob/main/.gitmodules). To update, run `git submodule update --init --remote`
