### ISSUE TITLE
Doesn't recognise directories on macOS

### ISSUE THREAD

**Issue by percheperche** [Ajatt-Tools/videoclip#14]
On macOS the home directory is `/Users/user` and it isn't recognised by videoclip.

**Comment by tatsumoto-ren** [comment]
macOS is considered unsafe to run since it's [proprietary malware](https://www.gnu.org/proprietary/malware-apple.html).  Try a free operating system like GNU/Linux.

**Comment by percheperche** [comment]
Shouldn't that apply even more to Windows as well? If so, why is it supported?

**Comment by tatsumoto-ren** [comment]
I don't know if Windows is actually supported or not, I never tested this add-on on Windows.

**Comment by percheperche** [comment]
But you do provide informations in the readme, meaning it is at least somewhat supported. Also I've personally tested it on Windows and it works.

**Comment by tatsumoto-ren** [comment]
It should work on macOS too then. Why doesn't it work?

**Comment by percheperche** [comment]
It doesn't recognise the directory for some reason.

**Comment by tatsumoto-ren** [comment]
Set `video_folder_path` and `audio_folder_path` in `videoclip.conf`. It should work then.

**Comment by percheperche** [comment]
I already have, it still doesn't work for some reason. It says the directory doesn't exist.

**Comment by tatsumoto-ren** [comment]
That's pretty sad. I don't know what may be causing it though.

**Comment by poteau** [comment]
> I already have, it still doesn't work for some reason. It says the directory doesn't exist.

Are you absolutely sure it exists? The default directory in this script is `Videos` which doesn't exist by default on macOS, so I had the same error. I created it and it worked for me without any config changes. If you don't want to create a new directory then just point it to your `Movies` folder, which should exist on any macOS installation.

**Comment by percheperche** [comment]
> > I already have, it still doesn't work for some reason. It says the directory doesn't exist.
> 
> Are you absolutely sure it exists? The default directory in this script is `Videos` which doesn't exist by default on macOS, so I had the same error. I created it and it worked for me without any config changes. If you don't want to create a new directory then just point it to your `Movies` folder, which should exist on any macOS installation.

I'm absolutely certain. I even created a "Videos" folder and it still said it doesn't exist. I've tried pointing it to the "Movies" folder, still the same error.

**Comment by poteau** [comment]
Okay, I took a closer look at the source code and that error seems to be thrown generically and might actually have nothing to do with directory access. It can actually fail and print the same error message if the `mpv` command isn't in your system's PATH. I was able to reproduce your error this way.

Is mpv accessible from the terminal for you? For example, if you go into the terminal and just type `mpv` does it return an error?

If it doesn't fail there, it could still fail within mpv if the PATH is somehow messed up (sometimes macOS desktop apps don't have access to homebrew stuff, this depends a lot on how you installed mpv and how your system is configured). Try opening the desktop mpv application, then type \` (tilde) to open mpv's console and then enter the command `run mpv`. There should be no output. If it says something like "[cplayer] Starting subprocess failed: init" that means mpv couldn't find the mpv command line binary, which this script needs in order to work.

**Comment by percheperche** [comment]
> Okay, I took a closer look at the source code and that error seems to be thrown generically and might actually have nothing to do with directory access. It can actually fail and print the same error message if the `mpv` command isn't in your system's PATH. I was able to reproduce your error this way.
> 
> Is mpv accessible from the terminal for you? For example, if you go into the terminal and just type `mpv` does it return an error?
> 
> If it doesn't fail there, it could still fail within mpv if the PATH is somehow messed up (sometimes macOS desktop apps don't have access to homebrew stuff, this depends a lot on how you installed mpv and how your system is configured). Try opening the desktop mpv application, then type ` (tilde) to open mpv's console and then enter the command `run mpv`. There should be no output. If it says something like "[cplayer] Starting subprocess failed: init" that means mpv couldn't find the mpv command line binary, which this script needs in order to work.

I have installed mpv using homebrew so I can access it from the terminal. Unfortunately the keyboard I'm using doesn't have the backtick character and using shortcuts doesn't work since mpv apparently only recognises them as they are (eg. Alt+9 instead of `), so I can't really test the console thing. Thank you for your help, will see if I can do anything to fix this.

**Comment by tatsumoto-ren** [comment]
> I can't really test the console thing.

you can still run `mpv` from the terminal to have the same effect.

**Comment by percheperche** [comment]
> > I can't really test the console thing.
> 
> you can still run `mpv` from the terminal to have the same effect.

He said that it could work with the terminal but fail within mpv, but even then I haved fixed it now and can confirm it doesn't give me any output so it should work. At least now I know that it works on macOS and it's just some kind of problem on my end.

**Comment by poteau** [comment]
The only other thing I can think of is to try running the command from the source code in your terminal on some video file and look for any errors. Something like this (change `input.mp4` at least though):

`mpv input.mp4 --loop-file=no --no-ocopy-metadata --no-sub --audio-channels=2 --oacopts-add=vbr=on --oacopts-add=application=voip --oacopts-add=compression_level=10 --vf-add=format=yuv420p --ovc=libx264 --oac=ogg --start=00:00:00 --end=00:00:02 --aid=1 --mute=auto --volume=100 --ovcopts-add=b=1M --oacopts-add=b=32k --ovcopts-add=crf=23 --ovcopts-add=preset=faster --vf-add=scale=-2:480 --ytdl-format=bestvideo+bestaudio/best -o=output.mp4`

I would be really surprised if that works.

**Comment by percheperche** [comment]
> The only other thing I can think of is to try running the command from the source code in your terminal on some video file and look for any errors. Something like this (change `input.mp4` at least though):
> 
> `mpv input.mp4 --loop-file=no --no-ocopy-metadata --no-sub --audio-channels=2 --oacopts-add=vbr=on --oacopts-add=application=voip --oacopts-add=compression_level=10 --vf-add=format=yuv420p --ovc=libx264 --oac=ogg --start=00:00:00 --end=00:00:02 --aid=1 --mute=auto --volume=100 --ovcopts-add=b=1M --oacopts-add=b=32k --ovcopts-add=crf=23 --ovcopts-add=preset=faster --vf-add=scale=-2:480 --ytdl-format=bestvideo+bestaudio/best -o=output.mp4`
> 
> I would be really surprised if that works.

Huh, interesting:

```
[encode] codec 'libx264' not found.
[encode] codec 'ogg' not found.
 (+) Video --vid=1 (*) (h264 1280x720 29.970fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
[encode] codec 'libx264' not found.
Error opening/initializing the selected video_out (--vo) device.
Video: no video

[encode] no data written to target file
Exiting... (Interrupted by error)
```

I guess I have a weird version of mpv/ffmpeg that is missing some basic codecs. Out of curiosity, how exactly did you install it?

**Comment by poteau** [comment]
I built mpv from source using this guide: https://gist.github.com/dbrookman/74b8bcfb37a23452f7137b83bca9580f. Ogg doesn't work for me either for some reason, so I just use aac for audio. I do have libx264 though. You could also try the other video options like vp9 or vp8 to see if that changes anything.

**Comment by tatsumoto-ren** [comment]
Why don't you just use GNU/Linux? I don't see why you'd want to jump through hoops trying to get a defective by design OS to work.

**Comment by poteau** [comment]
> Why don't you just use GNU/Linux? I don't see why you'd want to jump through hoops trying to get a defective by design OS to work.

Are you suggesting that using GNU/Linux doesn't also require jumping through hoops? I use it on some of my other machines, but I think it's misleading to suggest that it isn't defective in other ways. I just really like Apple's new ARM hardware and don't think Asahi is ready to replace macOS just yet.

Your scripts occasionally have issues working on macOS or Windows not necessarily because they have some fundamental flaw, but because you've admitted that you don't test for these platforms. It's that simple. 

Yes, debugging cross-platform issues is annoying. Yes, it would be more convenient from a developer's perspective if everyone used the same OS. Yes, it would be great if tech companies didn't spy on people with their evil proprietary software. I completely understand. Is GitHub really the place to try to convert people, though?

**Comment by poteau** [comment]
On that note, @tatsumoto-ren, I think a solution to this problem would be to add a config toggle to use ffmpeg instead of mpv to create clips, like in mpvacious. Sometimes the mpv binaries don't support all of the codecs for some reason. I think ffmpeg is more reliable for some users. On my old PC, mpvacious used to complain about missing codecs until I enabled the ffmpeg toggle.

**Comment by tatsumoto-ren** [comment]
> Are you suggesting that using GNU/Linux doesn't also require jumping through hoops?

GNU/Linux is friendlier to the user. It's not perfect of course, but you spend so much less time figuring out how to make things work.

Apple is very restrictive but at least I haven't heard that they prevent the user from replacing the proprietary operating system the computers come with. 

> Is GitHub really the place

All issues regarding https://github.com/Ajatt-Tools are discussed in our Matrix space. But I don't disable issues on GitHub just in case someone's lost.

>  add a config toggle to use ffmpeg

I agree with this. `ffmpeg` support was re-added to `mpvacoius` just recently, after a number of similar issues came up.

**Comment by percheperche** [comment]
Pretty sure I was doing something wrong when installing it because `brew link --overwrite mpv `solved the issue lol.

**Comment by mrfragger** [comment]
everything works fine on MacOS 
`brew install mpv --cask`
(--cask installs the icon too)

```
mpv --ovc-help
  --ovc=libvpx       libvpx VP8
  --ovc=libvpx-vp9   libvpx VP9
  --ovc=h264_videotoolbox VideoToolbox H.264 Encoder
  --ovc=hevc_videotoolbox VideoToolbox H.265 Encoder
  --ovc=prores_videotoolbox VideoToolbox ProRes Encoder
```

scripts/videoclip/videoclip.lua 
change libx264 to hevc_videotoolbox
for instance and you're good to go.

script-opts/videoclip.conf
```
video_folder_path=/Users/someusername/Movies/mpvclips/video
audio_folder_path=/Users/someusername/Movies/mpvclips/audio
```
same applies to webm. Use hevc_videotoolbox or h264_videotoolbox even though it's using ffmpeg.  Don't ask me why.  Thanks for the videoclip script.
