### ISSUE TITLE
Can't open the menu

### ISSUE THREAD

**Issue by TheLongLife** [Ajatt-Tools/videoclip#2]
I followed every step of the guide but when I press the hotkey nothing happens.

**Comment by tatsumoto-ren** [comment]
This is unexpected. Make sure your directory tree is set up right.
```
~/.config/mpv/scripts
|-- other_addon_1
|-- other_addon_2
`-- videoclip
    |-- main.lua
    |-- ...
    `-- videoclip.lua
```

**Comment by TheLongLife** [comment]
> This is unexpected. Make sure your directory tree is set up right.
> 
> ```
> ~/.config/mpv/scripts
> |-- other_addon_1
> |-- other_addon_2
> `-- videoclip
>     |-- main.lua
>     |-- ...
>     `-- videoclip.lua
> ```

Oh, my bad I didn't understand that the lua files should be put in the folder named "videoclip"
Works now! 
Thanks!

**Comment by tatsumoto-ren** [comment]
Glad it works!
