### ISSUE TITLE
encoder.lua:162: attempt to index local 'location_info' (a nil value)

### ISSUE THREAD

**Issue by WhitleyStriber** [Ajatt-Tools/videoclip#32]
[videoclip] Press 'c' to open the videoclip menu.
 (+) Video --vid=1 (*) (vp9 1920x1080 29.972fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
AO: [pipewire] 48000Hz stereo 2ch floatp
VO: [gpu] 1920x1080 yuv420p
[videoclip] Please wait...
[videoclip] The following args will be executed: mpv "/home/whitley/ff.webm" --loop-file=no --keep-open=no --no-ocopy-metadata --no-sub --audio-channels=2 --oacopts-add=vbr=on --oacopts-add=application=voip --oacopts-add=compression_level=10 --vf-add=format=yuv420p --sub-font-provider=auto --embeddedfonts=yes '--sub-font=Noto Sans CJK JP' --ovc=libx264 --oac=libopus --start=2.069 --end=79.279 --aid=1 --mute=no --volume=100.000000 --ovcopts-add=b=1M --oacopts-add=b=32k --ovcopts-add=crf=23 --ovcopts-add=preset=faster --vf-add=scale=-2:480 --ytdl-format= '--o=/home/drew/Pictures/mpv/Single Mom Goes VIRAL For Crying On Her Birthday Lets Break This Down _00m02s069ms-01m19s279ms.mp4' --sid=no --secondary-sid=no --sub-delay=0.000000 --sub-visibility=yes --secondary-sub-visibility=yes
[videoclip] 
[videoclip] stack traceback:
[videoclip] 	/home/whitley/.config/mpv/scripts/videoclip/videoclip.lua:283: in function 'create_clip'
[videoclip] 	/home/whitley/.config/mpv/scripts/videoclip/videoclip.lua:220: in function 'fn'
[videoclip] 	mp.defaults:230: in function 'fn'
[videoclip] 	mp.defaults:65: in function 'handler'
[videoclip] 	mp.defaults:382: in function 'handler'
[videoclip] 	mp.defaults:512: in function 'call_event_handlers'
[videoclip] 	mp.defaults:554: in function 'dispatch_events'
[videoclip] 	mp.defaults:505: in function <mp.defaults:504>
[videoclip] 	[C]: at 0x55e012716760
[videoclip] 	[C]: at 0x55e012714bd0
[videoclip] Lua error: /home/whitley/.config/mpv/scripts/videoclip/encoder.lua:162: attempt to index local 'location_info' (a nil value)

On Gentoo.

**Comment by tatsumoto-ren** [comment]
https://mpv.io/manual/master/#lua-scripting-utils-file-info(path)

apparently `utils.file_info(path)` returns nil when the path doesn't exist. for some reason this case is not handled properly. regardless, you likely need to create this directory (/home/drew/Pictures/mpv/).

**Comment by WhitleyStriber** [comment]
Had 1 letter wrong in the path. Thank you for clarifying how much of an idiot I am.
