### ISSUE TITLE
Subtitle background not clipping

### ISSUE THREAD

**Issue by Shichiha** [Ajatt-Tools/videoclip#33]
The subtitles' background is not clipped, like when you use `mpv file.mp4 --sub-back-color='#131415'`

**Comment by tatsumoto-ren** [comment]
Do you want to include the background in the produced clips?

**Comment by Shichiha** [comment]
yeah

**Comment by tatsumoto-ren** [comment]
Try appending the appropriate argument inside the `mkargs_video` function.

**Comment by tatsumoto-ren** [comment]
Cool!

You also need to create a PR with this change in order for other users to have it.
