### ISSUE TITLE
can't create a clip

### ISSUE THREAD

**Issue by zwb124** [Ajatt-Tools/videoclip#4]
Why can't I create a clip and always prompt me that the path doesn't exist? It still prompts me after using the absolute path

**Comment by tatsumoto-ren** [comment]
Does your version of mpv have the built-in encoder? If not, this add-on will fail.

**Comment by zwb124** [comment]
sorry,how to built-in encoder？

**Comment by tatsumoto-ren** [comment]
If you the encoder is present, you can run `mpv video.mkv -o=test.jpg` and it will produce a picture, for example. If it's not present, the command will fail.

**Comment by zwb124** [comment]
ok,thanks

**Comment by pkillnine** [comment]
I'm also getting this error, but I think my mpv has encoding compiled in, it works with `mpv <file> -o /tmp/test.mp4`.
