### ISSUE TITLE
Clip doesn't copy resolution from original video

### ISSUE THREAD

**Issue by ronandalton** [Ajatt-Tools/videoclip#5]
Why is it that the video gets resized by default when creating a clip? I would have thought most people would want to keep the original resolution when creating a clip, but there doesn't appear to be an option for this.

**Comment by ronandalton** [comment]
The solution I found was to set `video_height` to -2 in the config file copied from the readme. It'd still be nice if the resolution matched the original video by default though as I think that's what most people would want.

**Comment by tatsumoto-ren** [comment]
> I would have thought most people would want to keep the original resolution when creating a clip

Currently there is no option to keep the original resolution. Surprisingly, you are the first to suggest it. It's a good idea though, I'll see what I can do.
