### ISSUE TITLE
Fixed - FPS

### ISSUE THREAD

**Issue by Max-Enrik** [Ajatt-Tools/videoclip#7]
I'd like to choose a fixed **29fps**. So is it possible?

**Comment by tatsumoto-ren** [comment]
It is technically possible. Do you want to implement it for us?

**Comment by Max-Enrik** [comment]
I am not a code person. I wish I have to be able to do it by myself. But I can't.

**Comment by tatsumoto-ren** [comment]
I've added an option to specify FPS in the config file.

**Comment by Max-Enrik** [comment]
Very nice! Thank you!
