### ISSUE TITLE
More whitespaces to a whitespace

### ISSUE THREAD

**Issue by Max-Enrik** [Ajatt-Tools/videoclip#8]
I want to tweak this from `return str:gsub('[%c%p%s]', '')` to `return str:gsub('[%c%p]'%s{2,}', '')`.

Example name of a file:
`Video - Music Event 0001.mp4`

I expect:
`Video Music Event 0001.mp4`

**Comment by tatsumoto-ren** [comment]
Something like this should probably make more sense:

```
return str:gsub('[%-_]', ' '):gsub('[%c%p]', ''):gsub('%s+', ' ')
```

**Comment by tatsumoto-ren** [comment]
Plus, I'd also add a config switch to disable this functionality completely.

**Comment by Max-Enrik** [comment]
Thank you a lot.
